drivers/power/qpnp-bms: Fix missing data declaration
 drivers/power/qpnp-bms.c: In function 'set_battery_data':
 drivers/power/qpnp-bms.c:3652:17: error:
 'OPPO_14033_14013_nonstand_1700mAh_data' undeclared (first use in this
 function)
     batt_data = &OPPO_14033_14013_nonstand_1700mAh_data;

Signed-off-by: Joel Stanley <joel@jms.id.au>